### ISSUE TITLE
Malformed JSON: Expected: {, null

### ISSUE THREAD

**Issue by DevCobe** [ngenerio/smsghjs#1]
Error: Bad Request

"status":400,"text":"Malformed JSON: Expected: {, null"

i think it has to do with the JSON formatting.

**Comment by nanaeasiedu** [comment]
Hello @DevCobe, can you please give me more info on this issue. What function call did you make.

**Comment by DevCobe** [comment]
ok this the code i was testing

```
  `var tos = "23320******4",
  body = "Testing out the node js plugin for smsgh sms api.";

  var Message = SMSGH.Message
  var newMessage = new Message({from: 'Trackhab', to : tos, content: body})
  newSMSGH.messageApi.send(newMessage, function (err, res) {
        if(err){
                    console.log("sms err: "+err);
              }
        if(res){
                    console.log("sms response: "+JSON.stringify(res));
              }
  })`
```

it returns the error code 400

**Comment by nanaeasiedu** [comment]
Hi @DevCobe, checking it out. Will get back to you.

**Comment by nanaeasiedu** [comment]
@DevCobe It's fixed now. If you are using npm, update the `smsghjs` package. Thanks.

**Comment by DevCobe** [comment]
@ngenerio thanks yes am using the npm and have done the updates.
